CREATE TABLE HR.product(
	id varchar2(200),	
	name varchar2(200),	
	content varchar2(200),	
	price varchar2(200),	
	company varchar2(200),	
	img varchar2(200)	
);


SELECT * FROM product

SELECT * FROM product WHERE COMPANY = 'c100'

CREATE TABLE "HR"."BBS2" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 


CREATE TABLE "HR"."BBS3" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100) 
) 

ALTER TABLE HR.BBS3 
ADD CONSTRAINT BBS3_PK PRIMARY KEY ("no")

ALTER TABLE HR.BBS3 
ADD CONSTRAINT "FK_MEMBER33" FOREIGN KEY ("WRITER") REFERENCES "HR"."MEMBER" ("ID")

CREATE TABLE "HR"."DEPART2"(
	"ID" VARCHAR2(100),
	"NAME" VARCHAR2(100),
	"INSTRUCTOR" VARCHAR2(100),
	CONSTRAINT "DEPART2_PK" PRIMARY KEY ("ID")
)

CREATE TABLE "HR"."STUDENT2"(
	"ID" VARCHAR2(100),
	"NAME" VARCHAR2(100),
	"TEL" VARCHAR2(100)
)

ALTER TABLE HR.STUDENT2
ADD CONSTRAINT "STUDENT2_PK" PRIMARY KEY ("ID")


ALTER TABLE HR.STUDENT2
ADD CONSTRAINT "FK_STUDENT22" 
FOREIGN KEY ("ID") 
REFERENCES "HR"."DEPART2" ("ID")

CREATE TABLE MEMBER22
AS SELECT * FROM MEMBER

INSERT INTO MEMBER22 
VALUES ('BANANA2','BANANA2','BANANA2','BANANA2', SYSDATE)

INSERT INTO MEMBER22 
VALUES ('BANANA4','BANANA4','BANANA4','BANANA4', SYSDATE, 'AAA')



CREATE TABLE "HR"."BBS4" 
   (	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK" PRIMARY KEY ("no"), 
     CONSTRAINT "FK_MEMBER" FOREIGN KEY ("WRITER")
	 REFERENCES "HR"."MEMBER" ("ID") 
)

INSERT INTO BBS3
VALUES (BBS_ID_SEQ.NEXTVAL, 'HAPPY', 'HAAPY DAY', 'ICE')

CREATE SEQUENCE PD_ID_SEQ 
INCREMENT BY 1 
START WITH 1

CREATE TABLE PRODUCT2 (
	ID NUMBER (38, 0),
	NAME VARCHAR2(100)
)


INSERT INTO PRODUCT2 
VALUES (PD_ID_SEQ.NEXTVAL, 'SHOES')

SELECT * FROM PRODUCT2


CREATE TABLE "HR"."ORDERLIST3"( 
	ID NUMBER(38,0),
	TITLE VARCHAR2(100),
	PRICE NUMBER(38,0)
)

CREATE SEQUENCE OL3_ID_SEQ
INCREMENT BY 1
START WITH 1

INSERT INTO ORDERLIST3
VALUES (OL3_ID_SEQ.NEXTVAL , '타코야끼', 5000)

INSERT INTO ORDERLIST3
VALUES (OL3_ID_SEQ.NEXTVAL , '제로콜라' , 1500)

SELECT * FROM ORDERLIST3

SELECT * FROM ORDERLIST3
ORDER BY ID

SELECT * FROM ORDERLIST3
ORDER BY ID DESC


SELECT * FROM ORDERLIST3
WHERE ID >= 3
ORDER BY ID DESC


CREATE TABLE DEPT(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

CREATE TABLE EMP(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

CREATE TABLE SALGRADE(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT
PRIMARY KEY
(DEPTNO));



ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP
PRIMARY KEY
(EMPNO));

 

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO
FOREIGN KEY (DEPTNO)
REFERENCES DEPT (DEPTNO));



SELECT * FROM EMP -- SELECTION


SELECT DEPTNO FROM EMP --PROJECTION


SELECT DISTINCT DEPTNO FROM EMP --PROJECTION

SELECT ENAME, SAL*12 AS YEARSAL FROM EMP

SELECT * FROM EMP
ORDER BY SAL DESC

SELECT * FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO DESC

SELECT * FROM EMP
WHERE NOT DEPTNO = 30
ORDER BY EMPNO DESC


SELECT * FROM EMP
WHERE NOT DEPTNO = 30 AND JOB ='SALESMAN'

SELECT * FROM EMP
WHERE NOT DEPTNO = 30 OR JOB ='SALESMAN'

SELECT * FROM EMP
WHERE SAL >= 3000

SELECT * FROM EMP
WHERE SAL != 3000

SELECT * FROM EMP
WHERE JOB IN ('SALESMAN', 'MAMAGER')
ORDER BY JOB 

SELECT * FROM EMP
WHERE JOB NOT IN ('SALESMAN', 'MAMAGER')
ORDER BY JOB 

SELECT  * FROM EMP 
WHERE SAL BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT  * FROM EMP 
WHERE SAL NOT BETWEEN 2000 AND 3000
ORDER BY EMPNO

SELECT  * FROM EMP 
WHERE ENAME LIKE '_L%'

SELECT  * FROM EMP 
WHERE ENAME NOT LIKE '_L%'


SELECT  * FROM EMP 
WHERE COMM IS NULL 

SELECT  * FROM EMP 
WHERE COMM IS NOT NULL

CREATE TABLE DEPT_TEMP2
AS
SELECT * FROM DEPT

SELECT * FROM DEPT_TEMP2 

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'

UPDATE DEPT_TEMP2
SET DANME = 'DATABASE', LOC = 'BUSAN'
WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2
WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2


CREATE TABLE PRODUCT3
(	"ID" VARCHAR2(200),
"NAME" VARCHAR2(200),
"CONTENT" VARCHAR2(200),
"PRICE" NUMBER(38,0),
"COMPANY" VARCHAR2(200),
"IMG" VARCHAR2(200)
)

SELECT * FROM PRODUCT3 
ORDER BY PRICE DESC

SELECT NAME, CONTENT, PRICE FROM PRODUCT3
ORDER BY COMPANY

SELECT DISTINCT COMPANY FROM PRODUCT3

SELECT NAME, PRICE*12 AS PRICE5 FROM PRODUCT3

SELECT * FROM PRODUCT3 p 
WHERE PRICE = 3000

SELECT NAME, PRICE, COMPANY  FROM PRODUCT3 p 
WHERE PRICE BETWEEN 3000 AND 6000

SELECT NAME , COMPANY FROM PRODUCT3
WHERE COMPANY = 'c100'

SELECT NAME , COMPANY FROM PRODUCT3
WHERE NOT COMPANY = 'c100'

SELECT NAME , COMPANY FROM PRODUCT3
WHERE COMPANY = 'c100' OR COMPANY = 'c200'

SELECT * FROM PRODUCT3
WHERE NAME LIKE '%4'

SELECT * FROM PRODUCT3
WHERE NAME LIKE '%food%'

UPDATE PRODUCT3 
SET CONTENT = '품절'
WHERE PRICE = 5000

UPDATE PRODUCT3 
SET IMG = '0.PNG' , PRICE = 10000
WHERE ID ='100' OR ID = '102'

DELETE FROM PRODUCT3 p 
WHERE COMPANY  = 'C100'

DELETE PRODUCT3

